FROM postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB postgres
COPY ./sql/create_tables.sql /docker-entrypoint-initdb.d/
COPY ./sql/fill_tables.sql /docker-entrypoint-initdb.d/